/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import Dao.UserDAO;
import Entity.User;
import Panel.MenuItem;
import Panel.ChuyenTab;
import Panel.DanhMuc;
import Util.Auth;
import Util.MsgBox;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author tri03
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblVaiTro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlListMenu = new javax.swing.JPanel();
        jpnView = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mnuDoiMatKhau = new javax.swing.JMenuItem();
        mnuDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuThoat = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlMenu.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setBackground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logo.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Vai trò: ");

        lblVaiTro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVaiTro.setForeground(new java.awt.Color(255, 255, 51));
        lblVaiTro.setText("....");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Tên: ");

        lblTen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTen.setForeground(new java.awt.Color(255, 255, 51));
        lblTen.setText("....");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTen, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(lblVaiTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTen))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVaiTro)
                    .addComponent(jLabel4))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(null);

        pnlListMenu.setBackground(new java.awt.Color(0, 102, 255));
        pnlListMenu.setLayout(new javax.swing.BoxLayout(pnlListMenu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnlListMenu);

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnView.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mnuHeThong.setText("Hệ thống");

        mnuDoiMatKhau.setText("Đổi mật khẩu");
        mnuHeThong.add(mnuDoiMatKhau);

        mnuDangXuat.setText("Đăng xuất");
        mnuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuDangXuat);
        mnuHeThong.add(jSeparator1);

        mnuThoat.setText("Thoát");
        mnuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThoatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuThoat);

        jMenuBar1.add(mnuHeThong);

        mnuEdit.setText("Edit");
        jMenuBar1.add(mnuEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangXuatActionPerformed
        // TODO add your handling code here:
        mnuDangXuat();
    }//GEN-LAST:event_mnuDangXuatActionPerformed

    private void mnuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThoatActionPerformed
        // TODO add your handling code here:
        mnuThoat();
    }//GEN-LAST:event_mnuThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Main().setVisible(true);
//            }

            public void run() {
                new DangNhapFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPanel jpnView;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JMenuItem mnuDangXuat;
    private javax.swing.JMenuItem mnuDoiMatKhau;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenuItem mnuThoat;
    private javax.swing.JPanel pnlListMenu;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
    private void init() {
        setLocationRelativeTo(null);
        setTitle("Quản lí cửa hàng bán quần áo");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        ThongTinDangNhap();
        execute();
    }

    private void execute() {
        ImageIcon iconHH = new ImageIcon(getClass().getResource("/Icon/sanpham_32.png"));
        ImageIcon iconGD = new ImageIcon(getClass().getResource("/Icon/hoadon_32.png"));
        ImageIcon iconKM = new ImageIcon(getClass().getResource("/Icon/khuyenmai_32.png"));
        ImageIcon iconKH = new ImageIcon(getClass().getResource("/Icon/khachhang_32.png"));
        ImageIcon iconTK = new ImageIcon(getClass().getResource("/Icon/thongke_32.png"));
        ImageIcon iconNV = new ImageIcon(getClass().getResource("/Icon/nhanvien_32.png"));
        ImageIcon iconSubItem = new ImageIcon(getClass().getResource(""));

        MenuItem menuSP1 = new MenuItem(iconSubItem, "Sản Phẩm");
        MenuItem menuSP2 = new MenuItem(iconSubItem, "Chi Tiết Sản Phẩm");
        MenuItem menuSP3 = new MenuItem(iconSubItem, "Thuộc tính sản phẩm");

        MenuItem menuGD1 = new MenuItem(iconSubItem, "Bán Hàng");
        MenuItem menuGD2 = new MenuItem(iconSubItem, "Hóa Đơn");

        MenuItem menuTK1 = new MenuItem(iconSubItem, "Doanh Số");
        MenuItem menuTK2 = new MenuItem(iconSubItem, "Doanh Thu");

        MenuItem menuHH = new MenuItem(iconHH, "Hàng Hóa", menuSP1, menuSP2, menuSP3);
        MenuItem menuHD = new MenuItem(iconGD, "Giao Dịch", menuGD1, menuGD2);
        MenuItem menuKM = new MenuItem(iconKM, "Khuyến Mãi");
        MenuItem menuKH = new MenuItem(iconKH, "Khách Hàng");
        MenuItem menuTK = new MenuItem(iconTK, "Thống Kê", menuTK1, menuTK2);
        MenuItem menuNV = new MenuItem(iconNV, "Nhân Viên");

        addMenu(menuHH, menuHD, menuKM, menuKH, menuTK, menuNV);

        ChuyenTab ct = new ChuyenTab(jpnView);
        ct.setView(new SanPhamJpanel());

        List<DanhMuc> listItem = new ArrayList<>();

        listItem.add(new DanhMuc("HangHoa", menuHH));
        listItem.add(new DanhMuc("SanPham", menuSP1));
        listItem.add(new DanhMuc("MatHang", menuSP2));
        listItem.add(new DanhMuc("ThuocTinh", menuSP3));

        listItem.add(new DanhMuc("GiaoDich", menuHD));
        listItem.add(new DanhMuc("BanHang", menuGD1));
        listItem.add(new DanhMuc("HoaDon", menuGD2));

        listItem.add(new DanhMuc("KhuyenMai", menuKM));

        listItem.add(new DanhMuc("KhachHang", menuKH));

        if (lblVaiTro.getText().equals("Chủ")) {
            listItem.add(new DanhMuc("ThongKe", menuTK));
            listItem.add(new DanhMuc("DoanhSo", menuTK1));
            listItem.add(new DanhMuc("DoanhThu", menuTK2));

            listItem.add(new DanhMuc("NhanVien", menuNV));
        } else {
            javax.swing.UIManager.put("OptionPane.messageForeground", java.awt.Color.RED);
            MsgBox.alert(this, "BẠN LÀ NHÂN VIÊN!\nBạn không thể sử dụng chức năng [Thống Kê] và [Nhân Viên]");
        }

        ct.setEvent(listItem);
    }

    private void addMenu(MenuItem... menu) {
        for (int i = 0; i < menu.length; i++) {
            pnlListMenu.add(menu[i]);
            ArrayList<MenuItem> subMenu = menu[i].getSubMenu();
            for (MenuItem m : subMenu) {
                addMenu(m);
            }
        }
        pnlListMenu.revalidate();
    }

    private void mnuDangXuat() {
        Auth.clear();
        this.setVisible(false);
        ThongTinDangNhap();
    }

    private void mnuThoat() {
        if (MsgBox.confirm(this, "Bạn muốn thoát?")) {
            System.exit(0);
        }
    }

    public void ThongTinDangNhap() {
        try {
            if (Auth.isLogin() == false) {
                System.exit(0);
            } else {
                UserDAO daonv = new UserDAO();
                User nv = daonv.selectById(Auth.user.getIDUser());
                lblTen.setText(String.valueOf(nv.getTen()));
                if (nv.isVaiTro()) {
                    lblVaiTro.setText("Chủ");
                } else {
                    lblVaiTro.setText("Nhân Viên");
                }
                this.setVisible(true);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Đăng nhập thất bại");
        }

    }
}
