/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import Dao.AccountDAO;
import Dao.UserDAO;
import Entity.Account;
import Entity.User;
import Util.MsgBox;
import Util.XDate;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tri03
 */
public class NhanVienJpanel extends javax.swing.JPanel {

    /**
     * Creates new form NhanvienJpanel
     */
    public NhanVienJpanel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGioiTinh = new javax.swing.ButtonGroup();
        btnVaiTro = new javax.swing.ButtonGroup();
        btgTrangThai = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        txtMaUserDangNhap = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnSuaDangNhap = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongTinNhanVien = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtMaUser = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        btnThemNV = new javax.swing.JButton();
        btnTaoMoiNV = new javax.swing.JButton();
        btnXoaNV = new javax.swing.JButton();
        btnSuaNV = new javax.swing.JButton();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        lblGioiTinh = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtLuong = new javax.swing.JTextField();
        rdoNhanVien = new javax.swing.JRadioButton();
        blbVaiTro = new javax.swing.JLabel();
        rdoChu = new javax.swing.JRadioButton();
        rdoNghiLam = new javax.swing.JRadioButton();
        lblTrangThai = new javax.swing.JLabel();
        rdoConLam = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextPane();
        txtNgaySinh = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongTinDangNhap = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Thêm đăng nhập ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        txtMaUserDangNhap.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Mã User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        txtUsername.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        txtPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        btnSuaDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sua_32.png"))); // NOI18N
        btnSuaDangNhap.setText("Sửa");
        btnSuaDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDangNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaUserDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(txtUsername)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnSuaDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMaUserDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuaDangNhap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), " Thông tin nhân viên  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        tblThongTinNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã User", "Tên", "SDT", "Giới tính ", "Ngày sinh", "Email", "Địa chỉ", "Lương", "Vai trò", "Trang thái"
            }
        ));
        tblThongTinNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThongTinNhanVien);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), " Thêm nhân viên  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        txtMaUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), " Mã User ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        txtTen.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        txtSDT.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "SDT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        btnThemNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/them_32.png"))); // NOI18N
        btnThemNV.setText("Thêm");
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });

        btnTaoMoiNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/tao_moi_32.png"))); // NOI18N
        btnTaoMoiNV.setText("Tạo mới");
        btnTaoMoiNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiNVActionPerformed(evt);
            }
        });

        btnXoaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/xoa_32.png"))); // NOI18N
        btnXoaNV.setText("Xóa");
        btnXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNVActionPerformed(evt);
            }
        });

        btnSuaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sua_32.png"))); // NOI18N
        btnSuaNV.setText("Sửa");
        btnSuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNVActionPerformed(evt);
            }
        });

        rdoNam.setBackground(new java.awt.Color(255, 255, 255));
        btgGioiTinh.add(rdoNam);
        rdoNam.setText("Nam");

        rdoNu.setBackground(new java.awt.Color(255, 255, 255));
        btgGioiTinh.add(rdoNu);
        rdoNu.setText("Nữ");

        lblGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(0, 102, 102));
        lblGioiTinh.setText("Giới tính");

        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), " Email ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        txtLuong.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lương", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        rdoNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        btnVaiTro.add(rdoNhanVien);
        rdoNhanVien.setText("Nhân viên");

        blbVaiTro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        blbVaiTro.setForeground(new java.awt.Color(0, 102, 102));
        blbVaiTro.setText("Vai trò");

        rdoChu.setBackground(new java.awt.Color(255, 255, 255));
        btnVaiTro.add(rdoChu);
        rdoChu.setText("Chủ");

        rdoNghiLam.setBackground(new java.awt.Color(255, 255, 255));
        btgTrangThai.add(rdoNghiLam);
        rdoNghiLam.setText("Nghỉ làm");

        lblTrangThai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(0, 102, 102));
        lblTrangThai.setText("Trạng thái");

        rdoConLam.setBackground(new java.awt.Color(255, 255, 255));
        btgTrangThai.add(rdoConLam);
        rdoConLam.setText("Còn làm");

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Địa chỉ ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        txtDiaChi.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(txtDiaChi);

        txtNgaySinh.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), " Ngày Sinh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtMaUser, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtTen, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rdoConLam))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoNghiLam))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rdoChu)
                                        .addGap(6, 6, 6)
                                        .addComponent(rdoNhanVien))
                                    .addComponent(blbVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rdoNam)
                                        .addGap(6, 6, 6)
                                        .addComponent(rdoNu))
                                    .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane4))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTaoMoiNV, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGioiTinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoNam)
                            .addComponent(rdoNu))
                        .addGap(12, 12, 12)
                        .addComponent(blbVaiTro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoChu)
                            .addComponent(rdoNhanVien))
                        .addGap(8, 8, 8)
                        .addComponent(lblTrangThai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoConLam)
                            .addComponent(rdoNghiLam))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNV)
                    .addComponent(btnXoaNV)
                    .addComponent(btnTaoMoiNV)
                    .addComponent(btnSuaNV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thông tin đăng nhập ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        tblThongTinDangNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Mã User", "Username", "Password"
            }
        ));
        tblThongTinDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinDangNhapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblThongTinDangNhap);

        txtTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), " Tìm kiếm  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(102, 153, 0))); // NOI18N
        txtTimKiem.setPreferredSize(new java.awt.Dimension(300, 40));
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        // TODO add your handling code here:
        insertNhanVien();
    }//GEN-LAST:event_btnThemNVActionPerformed

    private void tblThongTinNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinNhanVienMouseClicked
        //        TODO add your handling code here:
        this.rownv = tblThongTinNhanVien.getSelectedRow();
        editNhanVien();
    }//GEN-LAST:event_tblThongTinNhanVienMouseClicked

    private void tblThongTinDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinDangNhapMouseClicked
        // TODO add your handling code here:
        this.rowdn = tblThongTinDangNhap.getSelectedRow();
        editDangNhap();
    }//GEN-LAST:event_tblThongTinDangNhapMouseClicked

    private void btnTaoMoiNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMoiNVActionPerformed
        // TODO add your handling code here:
        clearFormNhanVien();
    }//GEN-LAST:event_btnTaoMoiNVActionPerformed

    private void btnXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNVActionPerformed
        // TODO add your handling code here:
        deleteNhanVien();
    }//GEN-LAST:event_btnXoaNVActionPerformed

    private void btnSuaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNVActionPerformed
        // TODO add your handling code here:
        updateNhanVien();
    }//GEN-LAST:event_btnSuaNVActionPerformed

    private void btnSuaDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDangNhapActionPerformed
        // TODO add your handling code here:
        updateDangNhap();
    }//GEN-LAST:event_btnSuaDangNhapActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        searchNhanVien();
    }//GEN-LAST:event_txtTimKiemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blbVaiTro;
    private javax.swing.ButtonGroup btgGioiTinh;
    private javax.swing.ButtonGroup btgTrangThai;
    private javax.swing.JButton btnSuaDangNhap;
    private javax.swing.JButton btnSuaNV;
    private javax.swing.JButton btnTaoMoiNV;
    private javax.swing.JButton btnThemNV;
    private javax.swing.ButtonGroup btnVaiTro;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JRadioButton rdoChu;
    private javax.swing.JRadioButton rdoConLam;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNghiLam;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblThongTinDangNhap;
    private javax.swing.JTable tblThongTinNhanVien;
    private javax.swing.JTextPane txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaUser;
    private javax.swing.JTextField txtMaUserDangNhap;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
    private void init() {
        fillTableNhanVien();
        fillTableDangNhap();
    }
    // ==========================NHAN VIEN===============================
    int rownv = -1;
    UserDAO daonv = new UserDAO();

    private void fillTableNhanVien() {
        DefaultTableModel model = (DefaultTableModel) tblThongTinNhanVien.getModel();
        model.setRowCount(0);
        try {
            List<User> listnv = daonv.selectAll();
            for (User nv : listnv) {
                Object[] row = {
                    nv.getIDUser(),
                    nv.getTen(),
                    nv.getSDT(),
                    nv.isGioiTinh() ? "Nam" : "Nữ",
                    nv.getNgaySinh(),
                    nv.getEmail(),
                    nv.getDiaChi(),
                    nv.getLuong(),
                    nv.isVaiTro() ? "Chủ" : "Nhân Viên",
                    nv.isTrangThai() ? "Còn làm" : "Nghỉ làm"
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    private void clearFormNhanVien() {
        User nv = new User();
        txtMaUser.setText("");
        txtTen.setText("");
        txtSDT.setText("");
        rdoNam.isSelected();
        txtNgaySinh.setText(nv.getNgaySinh());
        txtEmail.setText("");
        txtDiaChi.setText("");
        txtLuong.setText("");
        rdoNghiLam.isSelected();
        rdoChu.isSelected();
    }

    User getFormNhanVien() {
        User nv = new User();
        nv.setIDUser(txtMaUser.getText());
        nv.setTen(txtTen.getText());
        nv.setSDT(txtSDT.getText());
        nv.setGioiTinh(rdoNam.isSelected());
        nv.setNgaySinh(txtNgaySinh.getText());
        nv.setEmail(txtEmail.getText());
        nv.setDiaChi(txtDiaChi.getText());
        nv.setLuong(Double.parseDouble(txtLuong.getText()));
        nv.setVaiTro(rdoChu.isSelected());
        nv.setTrangThai(rdoConLam.isSelected());
        return nv;
    }

    private void setFormUser(User nv) {
        txtMaUser.setText(String.valueOf(nv.getIDUser()));
        txtTen.setText(nv.getTen());
        txtSDT.setText(nv.getSDT());
        if (nv.isGioiTinh()) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        txtNgaySinh.setText(nv.getNgaySinh());
        txtEmail.setText(nv.getEmail());
        txtDiaChi.setText(nv.getDiaChi());
        txtLuong.setText(String.valueOf(nv.getLuong()));
        if (nv.isVaiTro()) {
            rdoChu.setSelected(true);
        } else {
            rdoNhanVien.setSelected(true);
        }
        if (nv.isTrangThai()) {
            rdoConLam.setSelected(true);
        } else {
            rdoNghiLam.setSelected(true);
        }
    }

    private void editNhanVien() {
        String idnv = (String) tblThongTinNhanVien.getValueAt(rownv, 0);
        User nv = daonv.selectById(idnv);
        setFormUser(nv);
    }

    private void insertNhanVien() {
        if (isValidatedNhanVien()) {
            User nv = getFormNhanVien();
            try {
                daonv.insert(nv);
                fillTableNhanVien();
                fillTableDangNhap();
                MsgBox.alert(this, "Thêm thành công!");
                //clearFormChiTietSanPham();
            } catch (Exception e) {
                MsgBox.alert(this, "Thêm thất bại!");
            }
        }
    }

    private void deleteNhanVien() {
        try {
            String idnv = (String) tblThongTinNhanVien.getValueAt(rownv, 0);
            User nv = daonv.selectById(idnv);
            daonv.delete(idnv);
            fillTableNhanVien();
            clearFormNhanVien();
            fillTableDangNhap();
            MsgBox.alert(this, "Xóa thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Xóa thất bại!");
        }
    }

    private void updateNhanVien() {
        if (isValidatedNhanVien()) {
            User nv = getFormNhanVien();
            try {
                daonv.update(nv);
                fillTableNhanVien();
                MsgBox.alert(this, "Cập nhật thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Cập nhật thất bại!");
            }
        }
    }

    boolean isValidatedNhanVien() {
        if (txtMaUser.getText().isEmpty()) {
            MsgBox.alert(this, "Không để trống mã nhân viên!");
            return false;
        }
        if (txtTen.getText().isEmpty()) {
            MsgBox.alert(this, "Không để trống họ và tên nhân viên!");
            return false;
        }
        try {
            if (txtSDT.getText().isEmpty()) {
                MsgBox.alert(this, "Số điện thoại chưa được nhập!");
                return false;
            }
            double salary = Double.parseDouble(txtSDT.getText());
            Pattern pattern = Pattern.compile("0\\d{7,10}");
            Matcher matcher = pattern.matcher(txtSDT.getText());
            if (!matcher.find()) {
                MsgBox.alert(this, "Định dạng số điện thoại không hợp lệ!");
                return false;
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Số điện thoại không hợp lệ (Phải là số)!");
            return false;
        }
        SimpleDateFormat sdf = new SimpleDateFormat();
        sdf.applyPattern("dd-MM-yyyy");
        try {
            if (txtNgaySinh.getText().isEmpty()) {
                MsgBox.alert(this, "Không để trống ngày sinh!");
                return false;
            }
            Date date = sdf.parse(txtNgaySinh.getText());
        } catch (Exception e) {
            MsgBox.alert(this, "Ngay khong hop le");
            return false;
        }
        try {
            if (txtEmail.getText().isEmpty()) {
                MsgBox.alert(this, "Email chưa được nhập!");
                txtEmail.requestFocus();
                return false;
            }
            Pattern pattern = Pattern.compile("\\w+@\\w+\\.\\w+");
            Matcher matcher = pattern.matcher(txtEmail.getText());
            if (!matcher.find()) {
                MsgBox.alert(this, "Định dạng email không hợp lệ!");
                return false;
            }
        } catch (HeadlessException e) {
        }
        try {
            if (txtLuong.getText().isEmpty()) {
                MsgBox.alert(this, "Số lương chưa được nhập!");
                return false;
            }
            double number = Double.parseDouble(txtLuong.getText());
            if (number < 0) {
                MsgBox.alert(this, "Số lương không được là số âm!");
                return false;
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lương không hợp lệ!!!");
            return false;
        }

        return true;
    }

    // ==========================DANG NHAP===============================
    int rowdn = -1;
    AccountDAO daodn = new AccountDAO();

    private void fillTableDangNhap() {
        DefaultTableModel model = (DefaultTableModel) tblThongTinDangNhap.getModel();
        model.setRowCount(0);
        try {
            List<Account> listdn = daodn.selectAll();
            for (Account dn : listdn) {
                Object[] row = {
                    dn.getIDUser(),
                    dn.getUserName(),
                    dn.getPassWord(),};
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    Account getFormDangNhap() {
        Account dn = new Account();
        dn.setIDUser(txtMaUserDangNhap.getText());
        dn.setUserName(txtUsername.getText());
        dn.setPassWord(txtPassword.getText());
        return dn;
    }

    private void setFormDangNhap(Account dn) {
        txtMaUserDangNhap.setText(String.valueOf(dn.getIDUser()));
        txtUsername.setText(String.valueOf(dn.getUserName()));
        txtPassword.setText(String.valueOf(dn.getPassWord()));
    }

    private void editDangNhap() {
        String iddn = (String) tblThongTinDangNhap.getValueAt(rowdn, 0);
        Account dn = daodn.selectById(iddn);
        setFormDangNhap(dn);
    }

    private void updateDangNhap() {
        Account dn = getFormDangNhap();
        try {
            daodn.update(dn);
            fillTableDangNhap();
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
        }
    }

    private void searchNhanVien() {
        DefaultTableModel model = (DefaultTableModel) tblThongTinNhanVien.getModel();
        model.setRowCount(0);
        try {
            String timkiem = txtTimKiem.getText();
            List<User> listnv = daonv.selectTimKiem(timkiem);
            for (User nv : listnv) {
                Object[] row = {
                    nv.getIDUser(),
                    nv.getTen(),
                    nv.getSDT(),
                    nv.isGioiTinh() ? "Nam" : "Nữ",
                    nv.getNgaySinh(),
                    nv.getEmail(),
                    nv.getDiaChi(),
                    nv.getLuong(),
                    nv.isVaiTro() ? "Chủ" : "Nhân Viên",
                    nv.isTrangThai() ? "Còn làm" : "Nghỉ làm"
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
}
